---
# Install HttpFS
- name: Install mapr-httpfs
  package: name=mapr-httpfs state=present

# Other actions
- name: Set owner mapr-system user
  file: path=/opt/mapr/httpfs owner={{ mapr_user }} group={{ mapr_group }} state=directory recurse=yes