---
# Install Spark on YARN
- name: Install mapr-spark
  package: name=mapr-spark state=present
- name: Find Spark Path
  find: paths="/opt/mapr/spark" patterns="spark*" file_type=directory
  register: spark_path_result
  failed_when: spark_path_result.matched != 1
- name: Find Hive Path
  find: paths="/opt/mapr/hive/" patterns="hive*" file_type=directory
  register: hive_path_result
  failed_when: hive_path_result.matched != 1
- name: Link hive-site.xml to Spark (otherwise Spark startup throws errors)
  file: src={{ hive_path_result.files[0].path }}/conf/hive-site.xml dest={{ spark_path_result.files[0].path }}/conf/hive-site.xml state=link
# Other actions
- name: Create maprfs:///apps/spark
  shell: hadoop fs -mkdir -p /apps/spark
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
  when: inventory_hostname == groups["mapr-spark-yarn"][0]
- name: Owner maprfs:///apps/spark
  shell: hadoop fs -chown mapr:mapr /apps/spark
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
  when: inventory_hostname == groups["mapr-spark-yarn"][0]
- name: Set owner mapr-system user
  file: path=/opt/mapr/spark owner={{ mapr_user }} group={{ mapr_group }} state=directory recurse=yes