- name: Installing MapR DRILL
  hosts: mapr-core
  tasks:
    - name: Create MapR volume
      debug: msg="Hello World"
- name: Installing MapR DRILL
  hosts: mapr-cldb
  tasks:
    - name: Create MapR volume
      debug: msg="Hello die ZWeite"
