# used by configure.sh and drill
- name: Setup global vars
  hosts: all
  roles:
    - mapr-global-vars
    - mapr-configure-vars
    - mapr-configure-vars-hs
- name: Install Hive WebHCat
  hosts: mapr-hive-webhcat
  roles:
    - mapr-hive-webhcat-install
- name: Uninstall Hive WebHCat
  hosts: all:!mapr-hive-webhcat
  roles:
    - mapr-hive-webhcat-uninstall