- name: Installing MapR DRILL
  hosts: all
  serial: "{{ serial|default(10) }}"
  tasks:
    - name: Create MapR volume
      mapr_volume:
        name: my.new.volume
        state: present
        path: /test
        read_ace: p
        write_ace: p
        min_replication: 2
        replication: 3
        soft_quota: 1T
        hard_quota: 2T
