- name: Installing MapR DRILL
  hosts: volumes
  tasks:
    - name: Create MapR volume
      mapr_volume:
        name: ansibletest
        state: present
        path: /aaab11
        read_ace: p
        write_ace: p
        min_replication: 2
        replication: 3
        soft_quota_in_mb: 2097152
        hard_quota_in_mb: 2097152
        accountable_entity_type: group
        accountable_entity_name: mapr
