#
# goto group_vars/all file and following properties:
# New repositories:
#  mapr_release_url: http://package.mapr.com/releases/v5.2.1
#  mapr_ecosystem_url: http://package.mapr.com/releases/MEP/MEP-3.0.0/
#
#
# Force restarts and reconfigure:
#  force_zookeeper_restart: true
#  force_warden_restart: true
#  force_reconfigure_sh: true
#
---
- name: Stop Warden
  hosts: mapr-core
  tasks:
  - name: Stop MapR Warden
    service: name=mapr-warden state=stopped
- name: Stop Zookeeper
  hosts: mapr-zookeeper
  tasks:
  - name: Stop Zookeeper
    service: name=mapr-zookeeper state=stopped
# Upgrade did not work. Hadoop packages got corrupted
- name: Uninstall old MapR packages
  hosts: mapr-core
  tasks:
  - name: Uninstall MapR packages
    package: name='mapr-*' state=absent
- import_playbook: site-cluster.yml
- name: Update version in MapR config
  hosts: mapr-core
  tasks:
  - name: Upgrade
    shell: 'maprcli config save -values {"mapr.targetversion":"`cat /opt/mapr/MapRBuildVersion`"}'
    environment:
      MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket