- name: Setup MapR repositories
  hosts: mapr-core
  roles:
    - mapr-configure-repository
- name: Apply common configuration to all nodes
  hosts: common
  roles:
    - common-prereq
    - common-selinux
    - {role: common-oraclejdk18, when: jdk == 'oraclejdk18'}
    - {role: common-openjdk18, when: jdk == 'openjdk18'}
    - {role: common-mapruser, when: mapr_create_user == true}
    - common-rpcbind
    - common-ntp
    - common-misc
    - common-sysctl
# used by configure.sh and drill
- name: Setup global vars
  hosts: all
  roles:
    - mapr-configure-vars
    - mapr-configure-vars-hs
- name: Install MapR Core
  hosts: mapr-core
  roles:
    - mapr-core-install
    - mapr-configure-subnets
- name: Install Zookeeper
  hosts: mapr-zookeeper
  roles:
    - mapr-zookeeper-install
- name: Uninstall Zookeeper
  hosts: all:!mapr-zookeeper
  roles:
    - mapr-zookeeper-uninstall
- name: Install CLDB
  hosts: mapr-cldb
  roles:
    - mapr-cldb-install
- name: Install CLDB
  hosts: all:!mapr-cldb
  roles:
    - mapr-cldb-uninstall
- name: Install Gateway
  hosts: mapr-gateway
  roles:
    - mapr-gateway-install
- name: Uninstall Gateway
  hosts: all:!mapr-gateway
  roles:
    - mapr-gateway-uninstall
- name: Install Filesystem, MapReduce2, YARN Node Manager
  hosts: mapr-datanode
  roles:
    - mapr-fileserver-install
    - mapr-mapreduce2-install
    - mapr-nodemanager-install
- name: Uninstall Filesystem, MapReduce2, YARN Node Manager
  hosts: all:!mapr-datanode
  roles:
    - mapr-fileserver-uninstall
    - mapr-mapreduce2-uninstall
    - mapr-nodemanager-uninstall
- name: Install YARN Resource Manager
  hosts: mapr-resourcemanager
  roles:
    - mapr-resourcemanager-install
- name: Uninstall YARN Resource Manager
  hosts: all:!mapr-resourcemanager
  roles:
    - mapr-resourcemanager-uninstall
- name: Install MySQL
  hosts: ext-mysql
  roles:
    - ext-mysql-install
- name: Uninstall MySQL
  hosts: all:!ext-mysql
  roles:
    - ext-mysql-uninstall
- name: Install MCS
  hosts: mapr-mcs
  roles:
    - mapr-mcs-install
- name: Uninstall MCS
  hosts: all:!mapr-mcs
  roles:
    - mapr-mcs-uninstall
- name: Install NFS
  hosts: mapr-nfs
  roles:
    - mapr-nfs-install
- name: Uninstall NFS
  hosts: all:!mapr-nfs
  roles:
    - mapr-nfs-uninstall
- name: Configure and start (unsecure)
  hosts: mapr-core
  roles:
   - {role: mapr-configure-unsecure, when: mapr_security == 'none'}
- name: Configure and start (native-security)
  hosts: mapr-core
  roles:
   - {role: mapr-configure-nativesecurity-secure, when: mapr_security == 'maprsasl'}
- name: Configure and start (kerberos)
  hosts: mapr-core
  roles:
   - {role: mapr-configure-kerberos, when: mapr_security == 'kerberos'}
- name: Restarting mapr-zookeeper
  hosts: mapr-zookeeper
  roles:
   - mapr-configure-zookeeper-restart
- name: Restarting mapr-warden
  hosts: mapr-core
  roles:
   - mapr-configure-warden-restart
- name: Install mapr-posix-client-basic (FUSE)
  hosts: mapr-posix-client-basic
  roles:
    - mapr-posix-client-basic-install
    - {role: mapr-patch-posix-client-basic-install, when: mapr_patch_url is defined and ansible_os_family != 'Debian'}
- name: Uninstall mapr-posix-client-basic (FUSE)
  hosts: all:!mapr-posix-client-basic
  roles:
    - mapr-patch-posix-client-basic-uninstall
    - mapr-posix-client-basic-uninstall
- name: Install mapr-posix-client-platinum (FUSE)
  hosts: mapr-posix-client-platinum
  roles:
    - mapr-posix-client-platinum-install
    - {role: mapr-patch-posix-client-platinum-install, when: mapr_patch_url is defined and ansible_os_family != 'Debian'}
- name: Uninstall mapr-posix-client-platinum (FUSE)
  hosts: all:!mapr-posix-client-platinum
  roles:
    - mapr-patch-posix-client-platinum-install
    - mapr-posix-client-platinum-install
- name: Install Drill Standalone
  hosts: mapr-drill-standalone
  roles:
    - mapr-drill-standalone-install
- name: Uninstall Drill Standalone
  hosts: all:!mapr-drill-standalone
  roles:
    - mapr-drill-standalone-uninstall
- name: Install Drill on YARN
  hosts: mapr-drill-yarn
  roles:
    - mapr-drill-yarn-install
- name: Uninstall Drill on YARN
  hosts: all:!mapr-drill-yarn
  roles:
    - mapr-drill-yarn-uninstall
- name: Install Flume
  hosts: mapr-flume
  roles:
    - mapr-flume-install
- name: Install Flume
  hosts: all:!mapr-flume
  roles:
    - mapr-flume-uninstall
- name: Install HBase CLI
  hosts: mapr-hbase-cli
  roles:
    - mapr-hbase-cli
- name: Install HBase REST and Thrift Server
  hosts: mapr-hbase-thrift-rest
  roles:
    - mapr-hbase-thrift-rest
- name: Install History Server
  hosts: mapr-historyserver
  roles:
    - mapr-historyserver-install
- name: Uninstall History Server
  hosts: all:!mapr-historyserver
  roles:
    - mapr-historyserver-uninstall
- name: Setup Hive Variables
  hosts: all
  vars:
      num_mysql_hosts: "{{ groups['ext-mysql']|length }}"
  roles:
    - mapr-hive-vars
    - {role: mapr-hive-mysql, when: hive_db_type == 'mysql' and hive_db_mysql_create_schema_and_user == true and num_mysql_hosts != '0'  }
- name: Install Hive CLI
  hosts: mapr-hive-cli
  roles:
    - mapr-hive-cli
- name: Install Hive MetaStore
  hosts: mapr-hive-metastore
  roles:
    - mapr-hive-metastore
- name: Install Hive Server 2
  hosts: mapr-hive-server2
  roles:
    - mapr-hive-server2
- name: Install Hive WebHCat
  hosts: mapr-hive-webhcat
  roles:
    - mapr-hive-webhcat
- name: Install Mahout
  hosts: mapr-mahout
  roles:
    - mapr-mahout-install
- name: Uninstall Mahout
  hosts: all:!mapr-mahout
  roles:
    - mapr-mahout-uninstall
- name: Install Pig
  hosts: mapr-pig
  roles:
    - mapr-pig-install
- name: Uninstall Pig
  hosts: all:!mapr-pig
  roles:
    - mapr-pig-uninstall
- name: Set Sqoop 2 Server Vars
  hosts: all
  roles:
    - mapr-sqoop2-server-vars
- name: Install Sqoop 2 Server
  hosts: mapr-sqoop2-server
  roles:
    - mapr-sqoop2-server-install
- name: Uninstall Sqoop 2 Server
  hosts: all:!mapr-sqoop2-server
  roles:
    - mapr-sqoop2-server-uninstall
- name: Install Sqoop 2 Client
  hosts: mapr-sqoop2-client
  roles:
    - mapr-sqoop2-client-install
- name: Uninstall Sqoop 2 Client
  hosts: all:!mapr-sqoop2-client
  roles:
    - mapr-sqoop2-client-uninstall
- name: Install HttpFS
  hosts: mapr-httpfs
  roles:
    - mapr-httpfs-install
- name: Uninstall HttpFS
  hosts: all:!mapr-httpfs
  roles:
    - mapr-httpfs-uninstall
- name: Set Oozie Vars
  hosts: all
  roles:
    - {role: mapr-oozie-mysql, when: oozie_db_type == 'mysql' and oozie_db_mysql_create_schema_and_user == true}
- name: Install Oozie
  hosts: mapr-oozie
  roles:
    - mapr-oozie-install
- name: Uninstall Oozie
  hosts: all:!mapr-oozie
  roles:
    - mapr-oozie-uninstall
- name: Install Spark on YARN
  hosts: mapr-spark-yarn
  roles:
    - mapr-spark-yarn-install
- name: Uninstall Spark on YARN
  hosts: all:!mapr-spark-yarn
  roles:
    - mapr-spark-yarn-uninstall
- name: Install Spark History Server
  hosts: mapr-spark-historyserver
  roles:
    - mapr-spark-historyserver-install
- name: Uninstall Spark History Server
  hosts: all:!mapr-spark-historyserver
  roles:
    - mapr-spark-historyserver-uninstall
- name: Setup Hue Vars
  hosts: all
  roles:
    - mapr-hue-vars
    - {role: mapr-hue-mysql, when: hue_db_type == 'mysql' and hue_db_mysql_create_schema_and_user == true}
- name: Install Hue
  hosts: mapr-hue
  roles:
    - mapr-hue-install
- name: Uninstall Hue
  hosts: all:!mapr-hue
  roles:
    - mapr-hue-uninstall
- name: Register roles and restart mapr-warden
  hosts: mapr-core
  roles:
    - mapr-configure-roles
# CHUFE restart really required? check.
#    - mapr-configure-warden-restart
- name: Install MapR collectd
  hosts: mapr-collectd
  roles:
    - mapr-collectd-install
- name: Uninstall MapR collectd
  hosts: all:!mapr-collectd
  roles:
    - mapr-collectd-uninstall
- name: Install MapR OpenTSDB
  hosts: mapr-opentsdb
  roles:
    - mapr-opentsdb-install
- name: Uninstall MapR OpenTSDB
  hosts: all:!mapr-opentsdb
  roles:
    - mapr-opentsdb-uninstall
- name: Install MapR Grafana
  hosts: mapr-grafana
  roles:
    - mapr-grafana-install
- name: Uninstall MapR Grafana
  hosts: all:!mapr-grafana
  roles:
    - mapr-grafana-uninstall
- name: MapR Configure Metrics Monitoring
  hosts: mapr-collectd
  roles:
    - mapr-metric-monitoring-configure
- name: Install MapR fluentd
  hosts: mapr-fluentd
  roles:
    - mapr-fluentd-install
- name: Uninstall MapR fluentd
  hosts: all:!mapr-fluentd
  roles:
    - mapr-fluentd-uninstall
- name: Install MapR ElasticSearch
  hosts: mapr-elasticsearch
  roles:
    - mapr-elasticsearch-install
- name: Uninstall MapR ElasticSearch
  hosts: all:!mapr-elasticsearch
  roles:
    - mapr-elasticsearch-uninstall
- name: Install MapR Kibana
  hosts: mapr-kibana
  roles:
    - mapr-kibana-install
- name: Uninstall MapR Kibana
  hosts: all:!mapr-kibana
  roles:
    - mapr-kibana-uninstall
- name: MapR Configure Log Monitoring
  hosts: mapr-fluentd
  roles:
    - mapr-log-monitoring-configure
- name: Restarting mapr-warden
  hosts: mapr-core
  roles:
   - mapr-configure-warden-restart
- name: MapR Patches
  hosts: mapr-core
  roles:
    - {role: mapr-patch, when: mapr_patch_url is defined and ansible_os_family != 'Debian'}

# CHUFE remove node from MCS with MAPR cli, execute on first CLDB.
# CHUFE stop warden, but before zookeeper -> zookeeper has core dep?
# CHUFE NFS loopback, NFS server and Fuse must be uninstalled in a group first, if a user wants to change nfs to fuse or vice versa
# CHUFE maybe do all uninstallations first?
- name: Uninstall MapR Core
  hosts: all:!mapr-core
  roles:
    - mapr-core-uninstall
