- name: Setup Hue Vars
  hosts: all
  roles:
    - mapr-hue-vars
- name: Install Hue
  hosts: mapr-hue
  roles:
    - mapr-hue
- name: Restarting mapr-warden
  hosts: mapr-core
  roles:
    - mapr-configure-warden-restart
