- name: Setup global vars
  hosts: all
  tasks:
    - name: Find Spark Path
      find: paths="/opt/mapr/spark" patterns="spark*" file_type=directory
      register: spark_path_result
      failed_when: spark_path_result.matched == 0
    - stat: path="{{ item.path }}/bin/spark-submit"
      with_items: "{{ spark_path_result.files }}"
      register: spark_paths
    - set_fact: spark_path="{{ spark_paths.results | selectattr('stat.exists', 'equalto', true) | map(attribute='item.path') | join('') }}"
    - debug: var=spark_path