- name: Setup Hue Vars
  hosts: all
  vars:
      num_mysql_hosts: "{{ groups['ext-mysql']|length }}"
  roles:
    - mapr-hue-vars
    - {role: mapr-hue-mysql, when: hue_db_type == 'mysql' and hue_db_mysql_create_schema_and_user == true and num_mysql_hosts != '0' }
- name: Install Hue
  hosts: mapr-hue
  roles:
    - mapr-hue-install
- name: Uninstall Hue
  hosts: all:!mapr-hue
  roles:
    - mapr-hue-uninstall