- name: Setup Hue Vars
  hosts: all
  roles:
    - mapr-hue-vars
    - {role: mapr-hue-mysql, when: hive_db_type == 'mysql' and hue_db_mysql_create_schema_and_user == true}
- name: Install Hue
  hosts: mapr-hue
  roles:
    - mapr-hue
- name: Register roles and restart mapr-warden
  hosts: mapr-core
  roles:
    - mapr-configure-roles
    - mapr-configure-warden-restart
- name: Install MapR collectd
  hosts: mapr-collectd
  roles:
    - mapr-collectd
- name: Install MapR OpenTSDB
  hosts: mapr-opentsdb
  roles:
    - mapr-opentsdb
- name: Install MapR Grafana
  hosts: mapr-grafana
  roles:
    - mapr-grafana
- name: MapR Configure Metrics Monitoring
  hosts: mapr-collectd
  roles:
    - mapr-metric-monitoring-configure
- name: Install MapR fluentd
  hosts: mapr-fluentd
  roles:
    - mapr-fluentd
- name: Install MapR ElasticSearch
  hosts: mapr-elasticsearch
  roles:
    - mapr-elasticsearch
- name: Install MapR Kibana
  hosts: mapr-kibana
  roles:
    - mapr-kibana
- name: MapR Configure Log Monitoring
  hosts: mapr-fluentd
  roles:
    - mapr-log-monitoring-configure
- name: Restarting mapr-warden
  hosts: mapr-core
  roles:
   - mapr-configure-warden-restart
- name: MapR Patches
  hosts: mapr-core
  roles:
    - {role: mapr-patch, when: mapr_patch_url is defined and ansible_os_family != 'Debian'}
