- name: Setup Spyglass ElasticSearch vars
  hosts: all
  roles:
    - mapr-log-monitoring-configure-vars
- name: Install MapR Kibana
  hosts: mapr-kibana
  roles:
    - mapr-kibana-install
- name: Copy keys to Kibana ElasticSearch nodes
  hosts: mapr-kibana
  roles:
    - {role: mapr-kibana-install-secure, when: spyglass_elasticsearch_secure}
- name: MapR Configure Log Monitoring
  hosts: mapr-fluentd
  roles:
    - mapr-log-monitoring-configure

