- name: Install Filesystem, MapReduce2, YARN Node Manager
  hosts: mapr-datanode
  roles:
    - mapr-fileserver-install
    - mapr-mapreduce2-install
    - mapr-nodemanager-install
- name: Uninstall Filesystem, MapReduce2, YARN Node Manager
  hosts: all:!mapr-datanode
  roles:
    - mapr-fileserver-uninstall
    - mapr-mapreduce2-uninstall
    - mapr-nodemanager-uninstall