- name: Setup global vars
  hosts: all
  roles:
    - mapr-global-vars
    - mapr-configure-vars
    - mapr-configure-vars-hs

- name: Install MapR collectd
  hosts: mapr-collectd
  roles:
    - mapr-collectd-install
- name: Uninstall MapR collectd
  hosts: all:!mapr-collectd
  roles:
    - mapr-collectd-uninstall
- name: Install Custom OpenTSDB
  hosts: mapr-opentsdb-custom
  roles:
    - mapr-opentsdb-custom-install
- name: Install MapR OpenTSDB
  hosts: mapr-opentsdb
  roles:
    - mapr-opentsdb-install
- name: Uninstall MapR OpenTSDB
  hosts: all:!mapr-opentsdb:!mapr-opentsdb-custom
  roles:
    - mapr-opentsdb-uninstall
- name: Install MapR Grafana
  hosts: mapr-grafana
  roles:
    - mapr-grafana-install
- name: Uninstall MapR Grafana
  hosts: all:!mapr-grafana
  roles:
    - mapr-grafana-uninstall
- name: MapR Configure Metrics Monitoring
  hosts: mapr-collectd
  roles:
    - mapr-metric-monitoring-configure
- name: Install MapR fluentd
  hosts: mapr-fluentd
  roles:
    - mapr-fluentd-install
- name: Uninstall MapR fluentd
  hosts: all:!mapr-fluentd
  roles:
    - mapr-fluentd-uninstall
- name: Install MapR ElasticSearch
  hosts: mapr-elasticsearch
  roles:
    - mapr-elasticsearch-install
- name: Uninstall MapR ElasticSearch
  hosts: all:!mapr-elasticsearch
  roles:
    - mapr-elasticsearch-uninstall
- name: Install MapR Kibana
  hosts: mapr-kibana
  roles:
    - mapr-kibana-install
- name: Uninstall MapR Kibana
  hosts: all:!mapr-kibana
  roles:
    - mapr-kibana-uninstall
- name: Setup Spyglass ElasticSearch vars
  hosts: all
  roles:
    - mapr-log-monitoring-configure-vars
- name: Generate keys for Spyglass ElasticSearch
  hosts: mapr-elasticsearch[0]
  roles:
    - {role: mapr-log-monitoring-configure-genkeys, when: spyglass_elasticsearch_secure}
- name: Copy keys to Spyglass ElasticSearch nodes
  hosts: mapr-elasticsearch
  roles:
    - {role: mapr-elasticsearch-install-secure, when: spyglass_elasticsearch_secure}
- name: Copy keys to Kibana ElasticSearch nodes
  hosts: mapr-kibana
  roles:
    - {role: mapr-kibana-install-secure, when: spyglass_elasticsearch_secure}
- name: MapR Configure Log Monitoring
  hosts: mapr-fluentd
  roles:
    - mapr-log-monitoring-configure
  serial: 1
- name: Uninstall MapR Core
  hosts: all:!mapr-core
  roles:
    - mapr-core-uninstall
- name: Unregister node vars
  hosts: all
  roles:
     - mapr-unregister-node-vars
- name: Unregister node vars
  hosts: mapr-cldb[0]
  vars:
     num_unprovision: "{{ groups['unprovision']|length }}"
  roles:
     - {role: mapr-unregister-node, when: num_unprovision != '0'}