---
- name: Create kerberos user for cluster
  ldap_entry:
    dn: "CN=mapr-{{ cluster_name }},{{ mapr_kerberos_ad_user_cn }}"
    state: present
#    start_tls: true
    objectClass:
      - organizationalPerson
      - person
      - top
      - user
    attributes:
      cn: "mapr-{{ cluster_name }}"
      displayName: "mapr-{{ cluster_name }}"
      name: "mapr-{{ cluster_name }}"
      sAMAccountName: "mapr-{{ cluster_name }}"
      instanceType: 4
#      unicodePwd:
      objectCategory: "{{ mapr_kerberos_ad_object_category }}"
      servicePrincipalName: "mapr/{{ cluster_name }}"
      userPrincipalName: "mapr/{{ cluster_name }}@{{ mapr_kerberos_domain }}"
      userAccountControl: 66080
    server_uri: "ldap://{{ mapr_kerberos_kdc }}/"
    bind_dn: "{{ mapr_kerberos_admin_bind_dn }}"
    bind_pw: "{{ mapr_kerberos_admin_bind_pw }}"
  when: inventory_hostname == groups["ext-kerberos"][0]

- name: Create kerberos users
  vars:
    kerbusers: ["mapr", "HTTP"]
  ldap_entry:
    dn: "CN={{ item }}-{{ ansible_hostname }},{{ mapr_kerberos_ad_user_cn }}"
    state: present
#    start_tls: true
    objectClass:
      - organizationalPerson
      - person
      - top
      - user
    attributes:
      cn: "{{ item }}-{{ ansible_hostname }}"
      displayName: "{{ item }}-{{ ansible_hostname }}"
      name: "{{ item }}-{{ ansible_hostname }}"
      sAMAccountName: "{{ item }}-{{ ansible_hostname }}"
      instanceType: 4
      objectCategory: "{{ mapr_kerberos_ad_object_category }}"
      servicePrincipalName: "{{ item }}/{{ ansible_fqdn }}"
      userPrincipalName: "{{ item }}/{{ ansible_fqdn }}@{{ mapr_kerberos_domain }}"
      userAccountControl: 66080
    server_uri: "ldap://{{ mapr_kerberos_kdc }}/"
    bind_dn: "{{ mapr_kerberos_admin_bind_dn }}"
    bind_pw: "{{ mapr_kerberos_admin_bind_pw }}"
  with_items: "{{ kerbusers }}"
    # http://stackoverflow.com/questions/4322243/adding-a-user-with-a-password-in-active-directory-ldaps
