---
# Uninstall YARN Resource Manager
- name: Stop YARN Resource Manager
  shell: maprcli node services -name resourcemanager -action stop -nodes {{ ansible_fqdn }}
  register: maprcli_result
  failed_when: maprcli_result.rc == 1 and maprcli_result.stdout.find('is not configured on node') == -1
  changed_when: maprcli_result.rc == 0
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
- name: Uninstall mapr-resourcemanager
  package: name=mapr-resourcemanager state=absent
