---
# Uninstall NFS
- name: Stop NFS server
  shell: maprcli node services -name nfs -action stop -nodes {{ ansible_fqdn }}
  register: maprcli_result
  failed_when: maprcli_result.rc == 1 and maprcli_result.stdout.find('is not configured on node') == -1
  changed_when: maprcli_result.rc == 0
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
- name: Uninstall mapr-nfs
  vars:
    packages_Suse: ['mapr-nfs']
    packages_RedHat: ['mapr-nfs']
    packages_Debian: ['mapr-nfs']
  package: name={{ item }} state=absent
  with_items: "{{ vars['packages_' + ansible_os_family] }}"

# Other actions
# conflicts with other posix clients
#- name: Remove /mapr dir
#  file: path=/mapr state=absent




