---
# - import_playbook: ext-mysql.yml
- name: Install MySQL
  hosts: all
  become: true
  roles:
    - ../../roles/ext-mysql-install
#   - name: Uninstall MySQL
#     hosts: all:!ext-mysql
#     roles:
#     - ../../roles/ext-mysql-uninstall

# - import_playbook: mapr-mep-hive.yml
- name: Setup Hive Variables
  hosts: all
  become: true
  vars:
    num_mysql_hosts: "{{ groups['ext-mysql']|length }}"
  roles:
    - ../../roles/mapr-hive-vars
    - {role: ../../roles/mapr-hive-mysql, when: hive_db_type == 'mysql' and hive_db_mysql_create_schema_and_user and num_mysql_hosts != '0'}
- name: Install Hive CLI
  hosts: all
  become: true
  roles:
    - ../../roles/mapr-hive-cli-install
- name: Install Hive MetaStore
  hosts: all
  become: true
  roles:
    - ../../roles/mapr-hive-metastore-install
- name: Install Hive Server 2
  hosts: all
  become: true
  roles:
    - ../../roles/mapr-hive-server2-install
#  - name: Install Hive WebHCat
#    hosts: mapr-hive-webhcat
#    roles:
#    - ../../roles/mapr-hive-webhcat-install
#  - name: Uninstall Hive WebHCat
#    hosts: all:!mapr-hive-webhcat
#    roles:
#    - ../../roles/mapr-hive-webhcat-uninstall
#  - name: Uninstall Hive Server 2
#    hosts: all:!mapr-hive-server2
#    roles:
#    - ../../roles/mapr-hive-server2-uninstall
#  - name: Uninstall Hive MetaStore
#    hosts: all:!mapr-hive-metastore
#    roles:
#    - ../../roles/mapr-hive-metastore-uninstall
#  - name: Uninstall Hive CLI
#    hosts: all:!mapr-hive-cli
#    roles:
#    - ../../roles/mapr-hive-cli-uninstall

# - import_playbook: ../../sites/mapr-mep-spark.yml

- name: Install Spark on YARN
  hosts: all
  become: true
  roles:
    - ../../roles/mapr-spark-yarn-install
#  - name: Uninstall Spark on YARN
#    # mapr-spark-historyserver installs mapr-spark as a dependency
#    hosts: all:!mapr-spark-yarn:!mapr-spark-historyserver
#    roles:
#    - ../../roles/mapr-spark-yarn-uninstall

#  - name: Install Spark Thrift Server
#    hosts: mapr-spark-thriftserver
#    roles:
#    - ../../roles/mapr-spark-thriftserver-install
#  - name: Uninstall Spark Thrift Server
#    hosts: all:!mapr-spark-thriftserver
#    roles:
#    - ../../roles/mapr-spark-thriftserver-uninstall
- name: Install Spark History Server
  hosts: all
  become: true
  roles:
    - ../../roles/mapr-spark-historyserver-install
#  - name: Uninstall Spark History Server
#    hosts: all:!mapr-spark-historyserver
#    roles:
#    - ../../roles/mapr-spark-historyserver-uninstall

# - import_playbook: mapr-mep-oozie.yml
- name: Setup Zookeeper String
  hosts: all
  become: true
  roles:
    - ../../roles/mapr-configure-vars-zk
- name: Set Oozie Vars
  hosts: all
  become: true
  vars:
    num_mysql_hosts: "{{ groups['ext-mysql']|length }}"
  roles:
    - {role: ../../roles/mapr-oozie-mysql, when: oozie_db_type == 'mysql' and oozie_db_mysql_create_schema_and_user and num_mysql_hosts != '0'}
- name: Install Oozie
  hosts: all
  become: true
  roles:
    - ../../roles/mapr-oozie-install
#  - name: Uninstall Oozie
#    hosts: all:!mapr-oozie
#    roles:
#    - ../../roles/mapr-oozie-uninstall
