---
# Install Oozie and MySQL
- name: Install mapr-oozie
  package: name=mapr-oozie state=present

# Other
- name: Get MySQL Host
  set_fact: mysql_item={{ hostvars[item]['ansible_fqdn'] }}
  with_items:
    - "{{ groups['ext-mysql'] }}"
  register: mysql_hosts
#- debug: var=mysql_hosts
#- fail: msg="No MySQL / MariaDB was defined in inventory file."
#  when: "{{ mysql_hosts.skipped }}"
- name: Make MySQL Host String
  set_fact: oozie_db_host={{ mysql_hosts.results | map(attribute='ansible_facts.mysql_item') | list | join(',')}}
- name: Create oozie mysql db
  mysql_db: name={{ oozie_db_schema }} state=present login_host={{ oozie_db_host }} login_user={{ mapr_mysql_user }} login_password={{ mapr_mysql_password }}
- name: Find Oozie Path
  find: paths="/opt/mapr/oozie/" patterns="oozie*" file_type=directory
  register: oozie_path_result
  failed_when: oozie_path_result.matched != 1
- debug: msg="Oozie Path {{ oozie_path_result.files[0].path }}"
#- name: Downloading MySQL Driver
#  unarchive: src={{ mysql_jdbc_url }} dest=/tmp copy=no
#- name: Copy mysql driver
#  copy: remote_src=True src=/tmp/mysql-connector-java-{{ mysql_jdbc_version }}/mysql-connector-java-{{ mysql_jdbc_version }}-bin.jar dest={{ oozie_path_result.files[0].path }}/libext/
- name: Copy mysql driver
  copy: src=mysql-connector-java-5.1.40-bin.jar dest={{ oozie_path_result.files[0].path }}/libext/
- name: Configure oozie-site.xml - unsecure
  template: src=oozie-site.unsecure.xml dest={{ oozie_path_result.files[0].path }}/conf/oozie-site.xml
  when: httpfs_security == 'none'
- name: Configure oozie-site.xml - Kerberos
  template: src=oozie-site.kerberos.xml dest={{ oozie_path_result.files[0].path }}/conf/oozie-site.xml
  when: httpfs_security == 'kerberos'
- name: Run oozie-setup.sh
  command: "{{ oozie_path_result.files[0].path }}/bin/oozie-setup.sh -hadoop {{ hadoop_version }} /opt/mapr/hadoop/hadoop-{{ hadoop_version }}"
- name: Set owner mapr-system user
  file: path=/opt/mapr/oozie owner={{ mapr_user }} group={{ mapr_group }} state=directory recurse=yes


