---
- name: Copy mapr.keytab
  copy: src={{ mapr_kerberos_local_keytabs_dir }}/{{ ansible_fqdn }}.keytab dest=/tmp/mapr.keytab

- name: Verify mapr/<hostname> keytab
  command: kinit -k -t /tmp/mapr.keytab mapr/{{ ansible_fqdn }}@{{ mapr_kerberos_realm }}
- name: Display current ticket mapr
  command: klist
  register: klist_out
- debug: msg="{{ klist_out }}"
- name: Destroy current ticket
  command: kdestroy

- name: Verify HTTP/<hostname> keytab
  command: kinit -k -t /tmp/mapr.keytab HTTP/{{ ansible_fqdn }}@{{ mapr_kerberos_realm }}
- name: Display current ticket mapr
  command: klist
  register: klist_out
- debug: msg="{{ klist_out }}"
- name: Destroy current ticket
  command: kdestroy

- name: Verify Cluster keytab
  command: kinit -k -t /tmp/mapr.keytab mapr/{{ cluster_name }}
- name: Display current ticket mapr
  command: klist
  register: klist_out
- debug: msg="{{ klist_out }}"
- name: Destroy current ticket
  command: kdestroy

- name: Clean up existing keytab
  file: path=/tmp/mapr.keytab state=absent