---
# Install MapR log monitoring configure
- name: Configure.sh
  shell: /opt/mapr/server/configure.sh -R -ES {{ elasticsearch_string }}
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket