---
# Install Sqoop2 Server
- name: Install mapr-sqoop2-server
  package: name=mapr-sqoop2-server state=present

# Other actions
- name: Set owner mapr-system user
  file: path=/opt/mapr/sqoop owner={{ mapr_user }} group={{ mapr_group }} state=directory recurse=yes

- name: Find Sqoop path
  find: paths="/opt/mapr/sqoop/" patterns="sqoop*" file_type=directory
  register: sqoop_path_result
  failed_when: sqoop_path_result.matched != 1

- name: Configure sqoop.properties - unsecure
  template: src=sqoop.unsecure.properties dest={{ sqoop_path_result.files[0].path }}//conf/sqoop.properties
  when: sqoop_security == 'none'
- name: Configure sqoop.properties for Mapr-SASL
  template: src=sqoop.maprsasl.properties dest={{ sqoop_path_result.files[0].path }}//conf/sqoop.properties
  when: sqoop_security == 'maprsasl'
- name: Configure sqoop.properties for Kerberos
  template: src=sqoop.kerberos.properties dest={{ sqoop_path_result.files[0].path }}//conf/sqoop.properties
  when: sqoop_security == 'kerberos'