---
# Install Sqoop2 Server
- name: Install mapr-sqoop2-server
  package: name=mapr-sqoop2-server state=present
#- name: Create sqoop2 mysql db
#  mysql_db: name={{ sqoop_db_schema }} state=present login_host={{ sqoop_db_host }} login_user={{ mapr_mysql_user }} login_password={{ mapr_mysql_password }}
# Other actions
- name: Set owner mapr-system user
  file: path=/opt/mapr/sqoop owner={{ mapr_user }} group={{ mapr_group }} state=directory recurse=yes

- name: Find Sqoop path
  find: paths="/opt/mapr/sqoop/" patterns="sqoop*" file_type=directory
  register: sqoop_path_result
  failed_when: sqoop_path_result.matched != 1

- name: Configure sqoop.properties - unsecure
  template: src=sqoop.unsecure.properties dest={{ sqoop_path_result.files[0].path }}//conf/sqoop.properties
  when: sqoop_security == 'none'
- name: Configure sqoop.properties for Mapr-SASL
  template: src=sqoop.maprsasl.properties dest={{ sqoop_path_result.files[0].path }}//conf/sqoop.properties
  when: sqoop_security == 'maprsasl'
- name: Configure sqoop.properties for Kerberos
  template: src=sqoop.kerberos.properties dest={{ sqoop_path_result.files[0].path }}//conf/sqoop.properties
  when: sqoop_security == 'kerberos'

#- debug: msg="Sqoop Path {{ sqoop_path_result.files[0].path }}"
#- name: Copy mysql driver
#  copy: src=mysql-connector-java-5.1.40-bin.jar dest={{ sqoop_path_result.files[0].path }}/server/lib/