- import_playbook: mapr-include-vars.yml
- name: Setup Zookeeper String
  hosts: all
  roles:
    - ../roles/mapr-configure-vars-zk
- name: Install HBase CLI
  hosts: mapr-hbase-cli
  roles:
    - ../roles/mapr-hbase-cli-install