- import_playbook: mapr-include-vars.yml
- name: Test user
  hosts: all
  tasks:
  - name: Set node to maintenance mode
    shell: "maprcli node maintenance -nodes {{ ansible_fqdn }} -timeoutminutes 1440"
    environment:
      MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
  - name: Stop MapR Warden
    service: name=mapr-warden state=stopped enabled=yes
  - name: Copy mfs.log-3 to backup
    copy: remote_src=True src=/opt/mapr/logs/mfs.log-3 dest=/opt/mapr/logs/mfs.log-3.bak backup=true
  - name: Remove old mfs.log-3 so that search for MFS start can be performed
    file: path=/opt/mapr/logs/mfs.log-3 state=absent
  - name: Start MapR Warden
    service: name=mapr-warden state=started enabled=yes
  - name: Wait for MFS to be started
    wait_for: path=/opt/mapr/logs/mfs.log-3 state=present search_regex="Registered with cldb" timeout=86400
  - name: Waiting for MFS container resync.
    shell: /opt/mapr/server/mrconfig info containers resync
    failed_when: false
    check_mode: no
    register: resync_result
    retries: 8640 # max a day :-)
    delay: 2 # TODO back to 10
    until: resync_result.rc == 0 and (resync_result.stdout_lines | reject('search','^---') | reject('search','^Time') | reject('search','^$') | list | count) == 0
    environment:
      MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
  - name: Set node to maintenance mode
    shell: "maprcli node maintenance -nodes {{ ansible_fqdn }} -timeoutminutes 0"
    environment:
      MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
  - debug: var=resync_result
