---
# Restart  Warden
- name: Restart MapR Warden
  service: name=mapr-warden state=restarted enabled=yes
- pause: seconds=30
  when: ansible_ckeck_mode is defined and not ansible_ckeck_mode
- name: Check if MapR Fileserver is running
  shell: "/opt/mapr/initscripts/mapr-mfs status"
  register: mfs_status
  failed_when: mfs_status.stdout.find('is running') == -1
