---
# Uninstall CLDB
- name: Uninstall mapr-cldb
  package: name=mapr-cldb state=absent
  register: cldb_result
- set_fact: cldb_haschanged={{ cldb_haschanged | int + 1 }}
  when: cldb_result.changed
