---
# Uninstall CLDB
- name: Stop CLDB
  shell: maprcli node services -name cldb -action stop -nodes {{ ansible_fqdn }}
  register: maprcli_result
  failed_when: maprcli_result.rc == 1 and maprcli_result.stdout.find('is not configured on node') == -1
  changed_when: maprcli_result.rc == 0
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
- name: Uninstall mapr-cldb
  package: name=mapr-cldb state=absent
  register: cldb_result
- set_fact: cldb_haschanged={{ cldb_haschanged | int + 1 }}
  when: cldb_result.changed
