---
- name: Install OpenJDK 1.8.0
  vars:
    packages_Suse: ['java-1.8.0-openjdk', 'java-1.8.0-openjdk-devel', 'java-1.8.0-openjdk-headless']
    packages_Redhat: ['openjdk-8-jdk', 'openjdk-8-jdk-headless']
    packages_Debian: ['java-1_8_0-openjdk', 'java-1_8_0-openjdk-devel', 'java-1_8_0-openjdk-headless']
  package: name={{ item }} state=present
  with_items: "{{ vars['packages_' + ansible_os_family] }}"
