---

- name: Group vars
  hosts: all
  tasks:
    - name: include global config
      include_vars: file="group_vars/all_vars"

- import_playbook: plays/common.yml
- import_playbook: plays/mapr-precheck.yml
- import_playbook: plays/mapr-repository.yml

- name: Check files
  hosts: all
  become: true
  tasks:
    # https://mapr.com/docs/home/ReferenceGuide/disksetup.html
    - name: Check storagefile1
      stat:
        path: /root/storagefile1
      register: storagefile1
    - name: Check storagefile2
      stat:
        path: /root/storagefile2
      register: storagefile2
    - name: Check storagefile3
      stat:
        path: /root/storagefile3
      register: storagefile3
- name: Prepare disk file
  hosts: all
  become: true
  tasks:
    # https://mapr.com/docs/home/ReferenceGuide/disksetup.html
    - name: Create empty file
      command: "dd if=/dev/zero of={{ item }} bs=1G count=5"
      with_items:
        - /root/storagefile1
        - /root/storagefile2
        - /root/storagefile3
      when: not storagefile1.stat.exists and not storagefile2.stat.exists and not storagefile3.stat.exists


- import_playbook: plays/mapr-core.yml

- name: post-install fixes
  hosts: all
  become: true
  tasks:
    - name: Modify /opt/mapr/initscripts/mapr-warden
      replace:
        path: "/opt/mapr/initscripts/{{ item.f }}"
        regexp: "{{ item.r }}"
        replace: coresDir=/opt/cores
      with_items:
        - r: coresDir=..dirname ...cat /proc/sys/kernel/core_pattern...
          f: mapr-warden
        - r: coresDir=..dirname ..cat /proc/sys/kernel/core_pattern..
          f: mapr-warden
        - r: coresDir=..dirname ...cat /proc/sys/kernel/core_pattern...
          f: mapr-gateway
        - r: coresDir=..dirname ..cat /proc/sys/kernel/core_pattern..
          f: mapr-gateway
        - r: coresDir=..dirname ...cat /proc/sys/kernel/core_pattern...
          f: mapr-cldb
        - r: coresDir=..dirname ..cat /proc/sys/kernel/core_pattern..
          f: mapr-cldb
    - name: set root password
      shell: echo "rootpass" | passwd --stdin root
    - name: set mapr password
      shell: echo "maprpass" | passwd --stdin mapr

- name: Restart cldb
  hosts: all
  gather_facts: false
  become: true
  roles:
    - ../roles/mapr-configure-warden-cldb-restart
      #    - ../roles/amadeus-mapr-configure-yarn-siteall

