---
# Uninstall YARN Node Manager
- name: Check for mapr-clusters.conf
  stat: path=/opt/mapr/conf/mapr-clusters.conf
  register: clusters_conf
- name: Stop YARN Node Manager
  shell: maprcli node services -name nodemanager -action stop -nodes {{ ansible_fqdn }}
  register: maprcli_result
  failed_when: maprcli_result.rc > 1
  changed_when: maprcli_result.rc == 0
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
  when: clusters_conf.stat.exists
- name: Uninstall mapr-nodemanager
  package: name=mapr-nodemanager state=absent
